import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, onValue, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";

const WORKS=["Conducting","DB Dressing","Room Wiring","18W Light Installation","Kitchen Switch Socket Installation","Fan Installation","Toilet Wiring","12W Light Installation","Toilet Switch Socket Installation"];
const REASONS=["Tile Work Pending","Material Not Available","Labour Not Available","False Ceiling Pending","Site Access Issue","Conducting not done","Other"];
const FLOORS=["Ground","First","Second","Third"], PFX={Ground:"G",First:"1F",Second:"2F",Third:"3F"};
const BUILDINGS=[{id:"B2",name:"Building 2",parts:[{id:"MAIN",name:"Building 2",rooms:88}]},{id:"B3",name:"Building 3",parts:[{id:"A",name:"Part A",rooms:52},{id:"B",name:"Part B",rooms:64},{id:"C",name:"Part C",rooms:52}]},{id:"B4",name:"Building 4",parts:[{id:"MAIN",name:"Building 4",rooms:104}]}];
function makeRooms(){const a=[];for(const b of BUILDINGS)for(const part of b.parts){const perFloor=part.rooms/4;for(const f of FLOORS)for(let n=1;n<=perFloor;n++)a.push({id:`${b.id}-${part.id}-${PFX[f]}-${String(n).padStart(2,"0")}`,building:b.id,buildingName:b.name,part:part.id,partName:part.name,floor:f,tasks:WORKS.map(work=>({work,status:"",reason:"",otherReason:"",remarks:""}))});}return a}
const fresh=makeRooms();
let data=JSON.parse(localStorage.getItem("roomsBuildingsV1")||"null")||fresh, current, db, saveTimer;
function setSync(text,cls=""){const e=$("syncStatus");e.textContent=text;e.className="syncstatus "+cls}
function pct(r){return Math.round(r.tasks.filter(t=>t.status==="Done"||t.status==="N/A").length/9*100)}
function roomStatus(r){const a=r.tasks.map(t=>t.status);if(a.every(x=>x==="Done"||x==="N/A"))return "Done";if(a.includes("In Progress"))return "In Progress";if(a.includes("Pending"))return "Pending";return "Not Started"}
function normalize(x){return x.map((r,i)=>{const f=fresh[i]||fresh[0];return {id:r.id||f.id,building:r.building||f.building,buildingName:r.buildingName||f.buildingName,part:r.part||f.part,partName:r.partName||f.partName,floor:r.floor||f.floor,tasks:WORKS.map((w,j)=>({...f.tasks[j],...(r.tasks?.[j]||{}),work:w}))}})}
function saveLocal(){localStorage.setItem("roomsBuildingsV1",JSON.stringify(data))}
function pushCloud(){if(!db)return;clearTimeout(saveTimer);setSync("Saving…","saving");saveTimer=setTimeout(()=>set(ref(db,"rooms"),data).then(()=>setSync("Live • Saved","ok")).catch(e=>{console.error(e);setSync("Offline • Local saved","offline")}),250)}
function render(){const total=data.length,done=data.filter(r=>roomStatus(r)==="Done").length,ip=data.filter(r=>roomStatus(r)==="In Progress").length,pe=data.filter(r=>roomStatus(r)==="Pending").length,overall=total?Math.round(data.reduce((s,r)=>s+pct(r),0)/total):0;$('stats').innerHTML=`<div class="stat"><b>${total}</b><span>Total Rooms</span></div><div class="stat"><b>${done}</b><span>Completed</span></div><div class="stat"><b>${ip}</b><span>In Progress</span></div><div class="stat"><b>${pe}</b><span>Pending</span></div><div class="stat wide"><b>${overall}%</b><span>Overall Completion</span></div>`;
$('floorCards').innerHTML=BUILDINGS.map(b=>b.parts.map(part=>{const a=data.filter(r=>r.building===b.id&&r.part===part.id),p=Math.round(a.reduce((s,r)=>s+pct(r),0)/Math.max(1,a.length));return `<div class="floorcard"><b>${b.name} • ${part.name}</b><div class="progress"><i style="width:${p}%"></i></div><small>${p}% • ${a.filter(r=>roomStatus(r)==="Done").length}/${a.length} done</small></div>`}).join('')).join('');
const q=$('search').value.toLowerCase(),b=$('buildingFilter').value,p=$('partFilter').value,f=$('floorFilter').value,st=$('statusFilter').value,list=data.filter(r=>(!q||r.id.toLowerCase().includes(q)||r.buildingName.toLowerCase().includes(q)||r.partName.toLowerCase().includes(q))&&(b==='ALL'||r.building===b)&&(p==='ALL'||r.part===p)&&(f==='ALL'||r.floor===f)&&(st==='ALL'||roomStatus(r)===st));$('roomCount').textContent=list.length+" rooms";$('rooms').innerHTML=list.map(r=>{const x=roomStatus(r),cl=x==="Done"?"done":x==="In Progress"?"ip":x==="Pending"?"pending":"ns";return `<div class="room" onclick="openRoom('${r.id}')"><div><b>${r.buildingName} • ${r.partName} • ${r.floor} • ${r.id.split('-').slice(-2).join('-')}</b><small>${pct(r)}%</small></div><span class="badge ${cl}">${x}</span></div>`}).join('')}
function refreshPartOptions(){const b=$('buildingFilter').value;const parts=b==='ALL'?[]:BUILDINGS.find(x=>x.id===b).parts;$('partFilter').innerHTML='<option value="ALL">All Parts</option>'+parts.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');if(b==='ALL')$('partFilter').value='ALL'}
["search","floorFilter","statusFilter"].forEach(id=>$(id).addEventListener("input",render));
$("buildingFilter").addEventListener("change",()=>{refreshPartOptions();render()});
$("partFilter").addEventListener("change",render);
refreshPartOptions();
window.openRoom=id=>{current=data.find(r=>r.id===id);$("modalTitle").textContent="Room "+id;$("modalPct").textContent=pct(current)+"% complete";$("tasks").innerHTML=current.tasks.map((t,i)=>taskHTML(t,i)).join("");$("modal").classList.remove("hidden");bindTasks()};
function taskHTML(t,i){const pending=t.status==="Pending",other=pending&&t.reason==="Other",auto=i>0&&t.reason==="Conducting not done";return `<div class="task" data-i="${i}"><div class="tasktitle">${i+1}. ${t.work}</div><div class="grid"><label>Status<select class="ts" ${auto?"disabled":""}><option value="">Select Status</option><option ${t.status==="Pending"?"selected":""}>Pending</option><option ${t.status==="In Progress"?"selected":""}>In Progress</option><option ${t.status==="Done"?"selected":""}>Done</option></select></label><label class="reasonWrap" style="display:${pending?"block":"none"}">Pending Reason<select class="reasonSel" ${auto?"disabled":""}><option value="">Select Reason</option>${REASONS.map(x=>`<option ${x===t.reason?"selected":""}>${x}</option>`).join("")}</select></label><label class="remarkWrap" style="display:${other?"block":"none"}">Remarks<textarea class="remarks" placeholder="Pending reason details...">${esc(t.remarks)}</textarea></label><div class="warn"></div></div></div>`}
function bindTasks(){document.querySelectorAll(".task").forEach(el=>{const s=el.querySelector(".ts"),rr=el.querySelector(".reasonWrap"),rs=el.querySelector(".reasonSel"),rw=el.querySelector(".remarkWrap");function update(){const pending=s.value==="Pending",other=pending&&rs.value==="Other";rr.style.display=pending?"block":"none";rw.style.display=other?"block":"none";if(!pending){rs.value="";rw.querySelector(".remarks").value=""}else if(rs.value!=="Other")rw.querySelector(".remarks").value=""}s.onchange=()=>{update();if(+el.dataset.i===0&&s.value==="Pending"){document.querySelectorAll(".task").forEach((x,j)=>{if(j>0){const ts=x.querySelector(".ts"),rs2=x.querySelector(".reasonSel"),rw2=x.querySelector(".remarks");ts.value="Pending";ts.disabled=true;rs2.value="Conducting not done";rs2.disabled=true;rw2.value="";x.querySelector(".reasonWrap").style.display="block";x.querySelector(".remarkWrap").style.display="none"}})}else if(+el.dataset.i===0){document.querySelectorAll(".task").forEach((x,j)=>{if(j>0){x.querySelector(".ts").disabled=false;x.querySelector(".reasonSel").disabled=false}})}};rs.onchange=update;update()})}
$("closeModal").onclick=()=>$("modal").classList.add("hidden");
$("saveRoom").onclick=()=>{if(document.querySelector('.task[data-i="0"] .ts').value==="Pending"){document.querySelectorAll(".task").forEach((el,j)=>{if(j>0){el.querySelector(".ts").value="Pending";el.querySelector(".reasonSel").value="Conducting not done"}})}let ok=true;document.querySelectorAll(".task").forEach(el=>{const i=+el.dataset.i,t=current.tasks[i],st=el.querySelector(".ts").value,r=el.querySelector(".reasonSel").value,rem=el.querySelector(".remarks").value.trim(),w=el.querySelector(".warn");w.textContent="";if(i>0&&current.tasks[0].status==="Pending"){Object.assign(t,{status:"Pending",reason:"Conducting not done",otherReason:"",remarks:""});return}if(st==="Pending"&&(!r||(r==="Other"&&!rem))){ok=false;w.textContent=r==="Other"?"Other reason details are required.":"Pending Reason is required.";return}Object.assign(t,{status:st,reason:st==="Pending"?r:"",otherReason:"",remarks:st==="Pending"&&r==="Other"?rem:""})});if(!ok){alert("Pending work ke liye Reason bharna zaroori hai. Other select karne par Remarks bhi zaroori hai.");return}saveLocal();render();$("modal").classList.add("hidden");pushCloud()};
function rows(){return data.flatMap(r=>r.tasks.map(t=>({Room:r.id,Floor:r.floor,Work:t.work,Status:t.status||"Not Started",PendingReason:t.status==="Pending"?(t.reason==="Other"?"Other":t.reason):"",Remarks:t.status==="Pending"&&t.reason==="Other"?t.remarks:""})))}
function csv(a){const k=Object.keys(a[0]||{}),q=x=>`"${String(x??"").replace(/"/g,'""')}"`;return "\uFEFF"+[k.map(q).join(","),...a.map(o=>k.map(x=>q(o[x])).join(","))].join("\r\n")}
function download(name,content,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("excelBtn").onclick=()=>download("104_Room_Checklist_Excel.csv",csv(rows()),"text/csv;charset=utf-8");$("pendingBtn").onclick=()=>download("104_Room_Pending_Report.csv",csv(rows().filter(x=>x.Status==="Pending")),"text/csv;charset=utf-8");$("summaryBtn").onclick=()=>download("104_Room_Summary.csv",csv(rows()),"text/csv;charset=utf-8");$("workerBtn").style.display="none";$("backupBtn").onclick=()=>download("104_Room_Checklist_Backup.json",JSON.stringify(data,null,2),"application/json");$("restoreInput").onchange=e=>{const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!Array.isArray(x)||x.length!==data.length)throw 0;data=normalize(x);saveLocal();render();pushCloud();alert("Backup restored successfully.")}catch{alert("Invalid backup file.")}};rd.readAsText(e.target.files[0])};$("clearBtn").onclick=()=>{if(confirm("All saved data will be deleted. Continue?")){data=fresh;saveLocal();render();pushCloud()}};
function migrateLegacy(){if(data.length===104&&data.every(r=>!r.building)){const target=fresh.filter(r=>r.building==='B4');data=data.map((r,i)=>({...target[i],tasks:r.tasks}));saveLocal()}}
migrateLegacy();
async function start(){const cfg=window.FIREBASE_CONFIG;if(!cfg||cfg.apiKey.startsWith("PASTE_")){setSync("Firebase setup required","offline");return}try{const app=initializeApp(cfg);const auth=getAuth(app);db=getDatabase(app);await signInAnonymously(auth);onAuthStateChanged(auth,user=>{if(!user)return;onValue(ref(db,"rooms"),snap=>{const v=snap.val();if(v){data=normalize(Array.isArray(v)?v:Object.values(v));saveLocal();render();setSync("Live • Synced","ok")}else{pushCloud();setSync("Live • Saved","ok")}},e=>{console.error(e);setSync("Offline • Local saved","offline")})})}catch(e){console.error(e);setSync("Setup error • Local only","offline")}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();start();
